name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: push to azure devops
        uses: actions/checkout@v2
        run: |
          git push --prune https://dev.azure.com/'${{secrets.AZURE_REPO}}' \
              +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*