name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: 'nginx'
          namespace: 'default'
          chart: 'app'
          token: '${{ github.token }}'
          value-files: "helm/values.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'