name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'nginx'
          namespace: 'default'
          chart: 'app'
          token: '${{ github.token }}'
          values: |
            name: foobar
          value_files: ["./helm/values.yaml"]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'